kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/webhookrelay/app

steps:
  - name: build
    image: golang:1.11.4
    commands:
      - cd cmd/app && go build

  - name: unit-test
    image: golang:1.11.4
    commands:
      - go test -v `go list ./... `